/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package peminjamanbuku;

import databukudkk.Novel;

/**
 *
 * @author acer
 */
public class BayarNovel extends javax.swing.JFrame {
    private static Novel novel;
    
    /**
     * Creates new form BayarNovel
     */
    public BayarNovel(Novel novel) {
        initComponents();
        juduln.setText("Judul : " + novel.getJudul());
        authorn.setText("Author : " + novel.getAuthor());
        penerbitn.setText("Penerbit : " + novel.getPenerbit());
        genren.setText("Genre : " + novel.getGenre());
        halamann.setText(String.valueOf("Halaman :" + novel.getHalaman()));
        stokn.setText(String.valueOf("Stok :" + novel.getStok()));
        hargan.setText(String.valueOf("Harga :" + novel.getHarga()));
        hargaperharin.setText(String.valueOf("Harga/Hari :" + novel.getHargaPerHari()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        juduln = new javax.swing.JLabel();
        authorn = new javax.swing.JLabel();
        penerbitn = new javax.swing.JLabel();
        genren = new javax.swing.JLabel();
        halamann = new javax.swing.JLabel();
        stokn = new javax.swing.JLabel();
        hargaperharin = new javax.swing.JLabel();
        hargan = new javax.swing.JLabel();
        buttonBayarkan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        jLabel1.setText("Pembayaran");

        juduln.setText("Judul");

        authorn.setText("Author");

        penerbitn.setText("Penerbit");

        genren.setText("Genre");

        halamann.setText("Halaman");

        stokn.setText("Stok");

        hargaperharin.setText("Harga/Hari");

        hargan.setText("Harga");

        buttonBayarkan.setText("Bayar!");
        buttonBayarkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBayarkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(juduln, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(authorn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(penerbitn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(genren, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(halamann, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(stokn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(hargan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(hargaperharin, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(buttonBayarkan))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(juduln)
                .addGap(14, 14, 14)
                .addComponent(authorn)
                .addGap(14, 14, 14)
                .addComponent(penerbitn)
                .addGap(14, 14, 14)
                .addComponent(genren)
                .addGap(14, 14, 14)
                .addComponent(halamann)
                .addGap(14, 14, 14)
                .addComponent(stokn)
                .addGap(14, 14, 14)
                .addComponent(hargan)
                .addGap(14, 14, 14)
                .addComponent(hargaperharin)
                .addGap(12, 12, 12)
                .addComponent(buttonBayarkan))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBayarkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBayarkanActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonBayarkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BayarNovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BayarNovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BayarNovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BayarNovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BayarNovel(novel).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorn;
    private javax.swing.JButton buttonBayarkan;
    private javax.swing.JLabel genren;
    private javax.swing.JLabel halamann;
    private javax.swing.JLabel hargan;
    private javax.swing.JLabel hargaperharin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel juduln;
    private javax.swing.JLabel penerbitn;
    private javax.swing.JLabel stokn;
    // End of variables declaration//GEN-END:variables
}
