/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package peminjamanbuku;

import databukudkk.Komik;

/**
 *
 * @author acer
 */
public class BayarKomik extends javax.swing.JFrame {
    private static Komik komik;

    /**
     * Creates new form BayarKomik
     */
    public BayarKomik(Komik komik) {
        initComponents();
        judulk.setText("Judul : " + komik.getJudul());
        authork.setText("Author : " + komik.getAuthor());
        penerbitk.setText("Penerbit : " + komik.getPenerbit());
        genrek.setText("Genre : " + komik.getGenre());
        jenisk.setText("Jenis : " + komik.getJenis());
        halamank.setText(String.valueOf("Halaman :" + komik.getHalaman()));
        stokk.setText(String.valueOf("Stok :" + komik.getStok()));
        hargak.setText(String.valueOf("Harga :" + komik.getHarga()));
        hargaperharik.setText(String.valueOf("Harga/Hari :" + komik.getHargaPerHari()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisk = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        judulk = new javax.swing.JLabel();
        authork = new javax.swing.JLabel();
        penerbitk = new javax.swing.JLabel();
        genrek = new javax.swing.JLabel();
        halamank = new javax.swing.JLabel();
        stokk = new javax.swing.JLabel();
        hargak = new javax.swing.JLabel();
        hargaperharik = new javax.swing.JLabel();
        buttonBayarkan = new javax.swing.JButton();

        jenisk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peminjamanbuku/bgImg.jpg"))); // NOI18N
        jenisk.setText("Jenis");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));
        getContentPane().setLayout(new nbimports.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        jLabel1.setText("Pembayaran");
        getContentPane().add(jLabel1, new nbimports.AbsoluteConstraints(6, 6, 150, -1));

        judulk.setText("Judul");
        getContentPane().add(judulk, new nbimports.AbsoluteConstraints(6, 48, 250, -1));

        authork.setText("Author");
        getContentPane().add(authork, new nbimports.AbsoluteConstraints(6, 76, 250, -1));

        penerbitk.setText("Penerbit");
        getContentPane().add(penerbitk, new nbimports.AbsoluteConstraints(6, 104, 250, -1));

        genrek.setText("Genre");
        getContentPane().add(genrek, new nbimports.AbsoluteConstraints(6, 132, 250, -1));

        halamank.setText("Halaman");
        getContentPane().add(halamank, new nbimports.AbsoluteConstraints(6, 160, 250, -1));

        stokk.setText("Stok");
        getContentPane().add(stokk, new nbimports.AbsoluteConstraints(6, 188, 250, -1));

        hargak.setText("Harga");
        getContentPane().add(hargak, new nbimports.AbsoluteConstraints(6, 216, 250, -1));

        hargaperharik.setText("Harga/Hari");
        getContentPane().add(hargaperharik, new nbimports.AbsoluteConstraints(6, 244, 250, -1));

        buttonBayarkan.setText("Bayar!");
        buttonBayarkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBayarkanActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBayarkan, new nbimports.AbsoluteConstraints(320, 270, 73, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBayarkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBayarkanActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonBayarkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BayarKomik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BayarKomik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BayarKomik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BayarKomik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BayarKomik(komik).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authork;
    private javax.swing.JButton buttonBayarkan;
    private javax.swing.JLabel genrek;
    private javax.swing.JLabel halamank;
    private javax.swing.JLabel hargak;
    private javax.swing.JLabel hargaperharik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jenisk;
    private javax.swing.JLabel judulk;
    private javax.swing.JLabel penerbitk;
    private javax.swing.JLabel stokk;
    // End of variables declaration//GEN-END:variables
}
