/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package peminjamanbuku;

/**
 *
 * @author acer
 */
public class BayarPembelajaran extends javax.swing.JFrame {
        static Pembelajaran pembelajaran;

    /**
     * Creates new form BayarPembelajaran
     */
    public BayarPembelajaran(Pembelajaran pembelajaran) {
        initComponents();
        judul.setText("Judul : " + pembelajaran.judul);
        author.setText("Author : " + pembelajaran.author);
        penerbit.setText("Penerbit : " + pembelajaran.penerbit);
        materi.setText("Materi : " + pembelajaran.materi);
        tingkatan.setText("Tingkatan : " + pembelajaran.tingkatan);
        halaman.setText(String.valueOf("Halaman :" + pembelajaran.halaman));
        stok.setText(String.valueOf("Stok :" + pembelajaran.stok));
        harga.setText(String.valueOf("Harga :" + pembelajaran.harga));
        hargaperhari.setText(String.valueOf("Harga/Hari :" + pembelajaran.hargaperhari));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bkomik = new javax.swing.JLabel();
        judul = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        penerbit = new javax.swing.JLabel();
        materi = new javax.swing.JLabel();
        halaman = new javax.swing.JLabel();
        tingkatan = new javax.swing.JLabel();
        stok = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        hargaperhari = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bkomik.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        bkomik.setText("Pembayaran");
        getContentPane().add(bkomik);
        bkomik.setBounds(6, 6, 144, 30);

        judul.setText("Judul");
        getContentPane().add(judul);
        judul.setBounds(6, 48, 300, 16);

        author.setText("Author");
        getContentPane().add(author);
        author.setBounds(6, 76, 300, 16);

        penerbit.setText("Penerbit");
        getContentPane().add(penerbit);
        penerbit.setBounds(6, 104, 300, 16);

        materi.setText("Materi");
        getContentPane().add(materi);
        materi.setBounds(6, 132, 300, 16);

        halaman.setText("Halaman");
        getContentPane().add(halaman);
        halaman.setBounds(6, 188, 300, 16);

        tingkatan.setText("Tingkatan");
        getContentPane().add(tingkatan);
        tingkatan.setBounds(6, 160, 300, 16);

        stok.setText("Stok");
        getContentPane().add(stok);
        stok.setBounds(6, 216, 300, 16);

        harga.setText("Harga");
        getContentPane().add(harga);
        harga.setBounds(6, 244, 300, 16);

        hargaperhari.setText("Harga/Hari");
        getContentPane().add(hargaperhari);
        hargaperhari.setBounds(6, 272, 300, 16);

        background2.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Pictures\\bg2.jpg")); // NOI18N
        getContentPane().add(background2);
        background2.setBounds(0, 0, 540, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BayarPembelajaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BayarPembelajaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BayarPembelajaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BayarPembelajaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BayarPembelajaran(pembelajaran).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel author;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel bkomik;
    private javax.swing.JLabel halaman;
    private javax.swing.JLabel harga;
    private javax.swing.JLabel hargaperhari;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel materi;
    private javax.swing.JLabel penerbit;
    private javax.swing.JLabel stok;
    private javax.swing.JLabel tingkatan;
    // End of variables declaration//GEN-END:variables
}
