/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package peminjamanbuku;

import databukudkk.Pembelajaran;

/**
 *
 * @author acer
 */
public class BayarPembelajaran extends javax.swing.JFrame {
    private static Pembelajaran pembelajaran;

    /**
     * Creates new form BayarPembelajaran
     */
    public BayarPembelajaran(Pembelajaran pembelajaran) {
        initComponents();
        judul.setText("Judul : " + pembelajaran.getJudul());
        author.setText("Author : " + pembelajaran.getAuthor());
        penerbit.setText("Penerbit : " + pembelajaran.getPenerbit());
        materi.setText("Materi : " + pembelajaran.getMateri());
        tingkatan.setText("Tingkatan : " + pembelajaran.getTingkatan());
        halaman.setText(String.valueOf("Halaman :" + pembelajaran.getHalaman()));
        stok.setText(String.valueOf("Stok :" + pembelajaran.getStok()));
        harga.setText(String.valueOf("Harga :" + pembelajaran.getHarga()));
        hargaperhari.setText(String.valueOf("Harga/Hari :" + pembelajaran.getHargaPerHari()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bkomik = new javax.swing.JLabel();
        judul = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        penerbit = new javax.swing.JLabel();
        materi = new javax.swing.JLabel();
        halaman = new javax.swing.JLabel();
        tingkatan = new javax.swing.JLabel();
        stok = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        hargaperhari = new javax.swing.JLabel();
        buttonBayarkan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new nbimports.AbsoluteLayout());

        bkomik.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        bkomik.setText("Pembayaran");
        getContentPane().add(bkomik, new nbimports.AbsoluteConstraints(6, 6, 144, -1));

        judul.setText("Judul");
        getContentPane().add(judul, new nbimports.AbsoluteConstraints(6, 48, 300, -1));

        author.setText("Author");
        getContentPane().add(author, new nbimports.AbsoluteConstraints(6, 76, 300, -1));

        penerbit.setText("Penerbit");
        getContentPane().add(penerbit, new nbimports.AbsoluteConstraints(6, 104, 300, -1));

        materi.setText("Materi");
        getContentPane().add(materi, new nbimports.AbsoluteConstraints(6, 132, 300, -1));

        halaman.setText("Halaman");
        getContentPane().add(halaman, new nbimports.AbsoluteConstraints(6, 188, 300, -1));

        tingkatan.setText("Tingkatan");
        getContentPane().add(tingkatan, new nbimports.AbsoluteConstraints(6, 160, 300, -1));

        stok.setText("Stok");
        getContentPane().add(stok, new nbimports.AbsoluteConstraints(6, 216, 300, -1));

        harga.setText("Harga");
        getContentPane().add(harga, new nbimports.AbsoluteConstraints(6, 244, 300, -1));

        hargaperhari.setText("Harga/Hari");
        getContentPane().add(hargaperhari, new nbimports.AbsoluteConstraints(6, 272, 300, -1));

        buttonBayarkan.setText("Bayar!");
        buttonBayarkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBayarkanActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBayarkan, new nbimports.AbsoluteConstraints(320, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBayarkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBayarkanActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonBayarkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BayarPembelajaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BayarPembelajaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BayarPembelajaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BayarPembelajaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BayarPembelajaran(pembelajaran).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel author;
    private javax.swing.JLabel bkomik;
    private javax.swing.JButton buttonBayarkan;
    private javax.swing.JLabel halaman;
    private javax.swing.JLabel harga;
    private javax.swing.JLabel hargaperhari;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel materi;
    private javax.swing.JLabel penerbit;
    private javax.swing.JLabel stok;
    private javax.swing.JLabel tingkatan;
    // End of variables declaration//GEN-END:variables
}
