/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package peminjamanbuku;

/**
 *
 * @author acer
 */
public class BayarKomik extends javax.swing.JFrame {
        static Komik komik;
    /**
     * Creates new form BayarKomik
     */
    public BayarKomik(Komik komik) {
        initComponents();
        judulk.setText("Judul : " + komik.judul);
        authork.setText("Author : " + komik.author);
        penerbitk.setText("Penerbit : " + komik.penerbit);
        genrek.setText("Genre : " + komik.genre);
        jenisk.setText("Jenis : " + komik.jenis);
        halamank.setText(String.valueOf("Halaman :" + komik.halaman));
        stokk.setText(String.valueOf("Stok :" + komik.stok));
        hargak.setText(String.valueOf("Harga :" + komik.harga));
        hargaperharik.setText(String.valueOf("Harga/Hari :" + komik.hargaperhari));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        judulk = new javax.swing.JLabel();
        authork = new javax.swing.JLabel();
        penerbitk = new javax.swing.JLabel();
        genrek = new javax.swing.JLabel();
        jenisk = new javax.swing.JLabel();
        halamank = new javax.swing.JLabel();
        stokk = new javax.swing.JLabel();
        hargak = new javax.swing.JLabel();
        hargaperharik = new javax.swing.JLabel();
        background3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        jLabel1.setText("Pembayaran");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 6, 150, 30);

        judulk.setText("Judul");
        getContentPane().add(judulk);
        judulk.setBounds(6, 48, 250, 16);

        authork.setText("Author");
        getContentPane().add(authork);
        authork.setBounds(6, 76, 250, 16);

        penerbitk.setText("Penerbit");
        getContentPane().add(penerbitk);
        penerbitk.setBounds(6, 104, 250, 16);

        genrek.setText("Genre");
        getContentPane().add(genrek);
        genrek.setBounds(6, 132, 250, 16);

        jenisk.setText("Jenis");
        getContentPane().add(jenisk);
        jenisk.setBounds(6, 160, 250, 16);

        halamank.setText("Halaman");
        getContentPane().add(halamank);
        halamank.setBounds(6, 188, 250, 16);

        stokk.setText("Stok");
        getContentPane().add(stokk);
        stokk.setBounds(6, 216, 250, 16);

        hargak.setText("Harga");
        getContentPane().add(hargak);
        hargak.setBounds(6, 244, 250, 16);

        hargaperharik.setText("Harga/Hari");
        getContentPane().add(hargaperharik);
        hargaperharik.setBounds(6, 272, 250, 16);

        background3.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Pictures\\bg2.jpg")); // NOI18N
        getContentPane().add(background3);
        background3.setBounds(0, 0, 550, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BayarKomik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BayarKomik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BayarKomik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BayarKomik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BayarKomik(komik).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authork;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel genrek;
    private javax.swing.JLabel halamank;
    private javax.swing.JLabel hargak;
    private javax.swing.JLabel hargaperharik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jenisk;
    private javax.swing.JLabel judulk;
    private javax.swing.JLabel penerbitk;
    private javax.swing.JLabel stokk;
    // End of variables declaration//GEN-END:variables
}
